In [1]:
from a3em.datasets import arden
import os
from pathlib import Path

In [2]:
prefetch_path = Path(os.getenv('PREFETCH_PATH'))
df = arden.load_data(prefetch_path)

In [3]:
df

,filename,rec_start,abs_begin,abs_end,duration,Selection,View,Channel,Begin Time (s),End Time (s),...,mel_mean_17,mel_mean_18,mel_mean_19,mel_mean_20,mel_mean_21,mel_mean_22,mel_mean_23,mel_mean_24,mel_mean_25,mel_mean_26
0,Arden_20250606_130050,2025-06-06 13:00:50,2025-06-06 13:08:44.246619,2025-06-06 13:08:49.858403,5.611785,5,Spectrogram 1,1,474.246619,479.858403,...,0.000770,0.000493,0.000297,0.000160,0.000071,0.000035,0.000014,6.908708e-06,4.140799e-06,3.324537e-06
1,Arden_20250606_130050,2025-06-06 13:00:50,2025-06-06 13:10:29.161466,2025-06-06 13:10:36.030277,6.868811,10,Spectrogram 1,1,579.161466,586.030277,...,0.002626,0.001343,0.000759,0.000399,0.000237,0.000103,0.000037,1.698509e-05,4.587930e-06,1.358824e-06
2,Arden_20250606_140055,2025-06-06 14:00:55,2025-06-06 14:12:16.560669,2025-06-06 14:12:20.784060,4.223391,3,Spectrogram 1,1,681.560669,685.784060,...,0.000312,0.000173,0.000114,0.000066,0.000037,0.000024,0.000017,1.330589e-05,1.193656e-05,1.160821e-05
3,Arden_20250606_140055,2025-06-06 14:00:55,2025-06-06 14:14:18.574893,2025-06-06 14:14:23.958556,5.383663,4,Spectrogram 1,1,803.574893,808.958556,...,0.000112,0.000053,0.000030,0.000015,0.000009,0.000007,0.000003,8.221679e-07,2.994502e-07,1.252941e-07
4,Arden_20250606_140055,2025-06-06 14:00:55,2025-06-06 14:16:52.798276,2025-06-06 14:16:58.506815,5.708539,9,Spectrogram 1,1,957.798276,963.506815,...,0.002868,0.001863,0.001036,0.000506,0.000245,0.000140,0.000053,1.659994e-05,3.562116e-06,2.657086e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,Arden_20250609_010150,2025-06-09 01:01:50,2025-06-09 01:20:55.467829,2025-06-09 01:21:00.126306,4.658477,None,None,1,1145.467829,1150.126306,...,0.014980,0.007991,0.004214,0.002829,0.001206,0.000578,0.000268,1.003752e-04,2.755178e-05,7.019392e-06
1121,Arden_20250609_010150,2025-06-09 01:01:50,2025-06-09 01:20:48.531828,2025-06-09 01:20:53.057961,4.526133,None,None,1,1138.531828,1143.057961,...,0.032677,0.020464,0.011351,0.007096,0.004640,0.001960,0.000870,2.810106e-04,1.040975e-04,6.406815e-05
1122,Arden_20250609_010150,2025-06-09 01:01:50,2025-06-09 01:46:28.428241,2025-06-09 01:46:32.849735,4.421495,None,None,1,2678.428241,2682.849735,...,0.081190,0.052919,0.032520,0.024138,0.012659,0.005548,0.003468,2.484822e-03,2.081033e-03,1.968795e-03
1123,Arden_20250609_010150,2025-06-09 01:01:50,2025-06-09 01:17:03.978125,2025-06-09 01:17:07.452831,3.474706,None,None,1,913.978125,917.452831,...,0.056519,0.028890,0.013597,0.010394,0.005021,0.001583,0.000675,2.316942e-04,4.610802e-05,7.748149e-06
1124,Arden_20250609_010150,2025-06-09 01:01:50,2025-06-09 01:41:17.047480,2025-06-09 01:41:21.561141,4.513662,None,None,1,2367.047480,2371.561141,...,0.005873,0.003165,0.002041,0.001589,0.000640,0.000263,0.000106,4.198464e-05,1.757547e-05,1.106111e-05

In [8]:
data = df[['quality', 'mel_mean_17']]
data

      quality  mel_mean_17
0           3     0.000770
1           3     0.002626
2           3     0.000312
3           4     0.000112
4           3     0.002868
...       ...          ...
1120        0     0.014980
1121        0     0.032677
1122        0     0.081190
1123        0     0.056519
1124        0     0.005873

[1309 rows x 2 columns]